# Generated by Django 4.1.2 on 2022-10-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_app',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='my_app',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
